ToExtractParams = [
    # "FADEC Bit-packed Trigger Word : CLIMB CONDITIONS DETECTED",
    "Offset",
    "Selected Core Compartment Cooling (CCC) Valve Position (%)",
    "Selected CAI (Cowl Anti Ice) Bleed Config",
    "Selected Booster Anti-Ice (BAI) Pressure (PSIA)",
    "Selected Transient Bleed Valve (TBV) Position (%)",
    "Selected Variable Bleed Valve (VBV) Position (%)",
    "Selected Variable Stator Vane (VSV) Position (%)",
    "Selected HP Turbine Active Clearance Control Valve Position (%)",
    "Selected LP Turbine Active Clearance Control Valve Position (%)",
    "Total Engine Horsepower Extraction (HP)",
    "Selected Mass Fuel Flow (PPH)",
    "Average Gas Temperature at Station 25 (DEG_C)",
    "Calculated Ambient Temperature (DEG_C)",
    "Selected Compressor Delay Total Temperature (DEG_C)",  # TT3
    "Selected Compressor Discharge Static Pressure (PSIA)",
    "Selected Ambient Static Pressure (PSIA)",
    "Selected Exhaust Gas Temperature (DEG_C)",
    "Selected HP Comp Inlet Total Temperature (DEG_C)",
    "Selected PT2 Pressure (PSIA)",
    "Selected Total Temperature at Station 12 (DEG_C)",
    "Selected Fan Speed (%)",
    "Corrected Fan Speed to Station 12 (%)",
    "Selected Core Speed (%)",
    "Corrected Core Speed to Station 25 (%)",
    "Core Speed Rate of Change (%N2/SEC)",
    "Altitude based on P0 (FT)",
    "UVL_FLIGHTPHS",
    "Selected Mach Number (MACH)",
    "Pitch Angle from Aircraft (DEGREES)",
    "Roll Angle from Aircraft (DEGREES)",
    "Calculated Core Airflow (PPS)",
    # "Calculated Fuel to Air Ratio"
    'Header: Start Date'
]